server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    include: user,trade
    active: dev
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/xlaoy?serverTimezone=UTC&useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#  datasource:
#    dbmaster:
#      jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/xlaoy?serverTimezone=UTC&useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#      username: root
#      password: 123456
#      driver-class-name: net.sf.log4jdbc.DriverSpy #com.mysql.cj.jdbc.Driver
#      type: com.zaxxer.hikari.HikariDataSource
#      maxPoolSize: 20
#    dbslave:
#      jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3307/xlaoy?serverTimezone=UTC&useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#      username: root
#      password: 123456
#      driver-class-name: net.sf.log4jdbc.DriverSpy #com.mysql.cj.jdbc.Driver
#      type: com.zaxxer.hikari.HikariDataSource
#      maxPoolSize: 20
#  sharding-jdbc:
#    master-slave-rule:
#      name: dataSource
#      masterDataSourceName: dbmaster
#      slaveDataSourceNames: dbslave
#      loadBalanceAlgorithmType: ROUND_ROBIN # 配置从库选择策略，提供轮询与随机，这里选择用轮询
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: none
#  redis:
#    database: 15
#    host: 10.200.157.139
#    port: 6379
#    password: Zchzredis2017
#    jedis:
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: 1
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: xlaoy
#    password: 123456
#    virtual-host: /xlaoy
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: xlaoy
#      username: xlaoy
#      password: ["1","2","3","4","5","6"]
#
#sharding:
#  jdbc:
#    datasource:
#      names: db_master,db_slave

#org.mybatis.spring.boot.autoconfigure.MybatisProperties
mybatis:
  configuration:
    map-underscore-to-camel-case: true #启驼峰命名转换
  #mapperLocations: classpath*:com/xlaoy/**/mapper/*.xml

# 熔断 HystrixCommandProperties  配置类 监控 http://m.blog.csdn.net/u012702547/article/details/78224483
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000
          semaphore:
            maxConcurrentRequests: 50

# 均衡负载  DefaultClientConfigImpl  配置类
ribbon:
  ConnectTimeout: 1000 #ribbon请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
  #OkToRetryOnAllOperations: true #对所有操作请求都进行重试
  #MaxAutoRetries: 1 #对当前实例的重试次数
  #MaxAutoRetriesNextServer: 1 #对下个实例的重试次数

# 开启服务降级
#feign:
#  hystrix:
#    enabled: true
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true

apibasicauth:
  services:
    xlaoy-server:
      username: xlaoy
      password: 123456

#打开actuator的所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

swagger:
  docket:
    actuate:
      title: actuate模块
      base-package: org.springframework.boot.actuate
    app:
      title: 系统应用模块
      base-package: com.xlaoy.starter
    taskclient:
      title: 定时任务客户端
      base-package: com.task.client